/**
 * Dutch names for all books, keyed by slug.
 * Used to replace `name_en` on read pages when locale === 'nl'.
 */
export const BOOK_NAMES_NL: Record<string, string> = {
  // Torah
  bereshit:              'Genesis',
  shemoth:               'Exodus',
  wayyiqra:              'Leviticus',
  bemidbar:              'Numeri',
  debarim:               'Deuteronomium',
  // Former Prophets
  yahusha:               'Jozua',
  shophetim:             'Richteren',
  ruth:                  'Ruth',
  'shemuel-aleph':       '1 Samuël',
  'shemuel-beth':        '2 Samuël',
  'melakim-aleph':       '1 Koningen',
  'melakim-beth':        '2 Koningen',
  // Writings
  'dibrey-hayamim-aleph':'1 Kronieken',
  'dibrey-hayamim-beth': '2 Kronieken',
  ezra:                  'Ezra',
  nehemyah:              'Nehemia',
  ester:                 'Esther',
  iyob:                  'Job',
  tehillim:              'Psalmen',
  mishley:               'Spreuken',
  qoheleth:              'Prediker',
  'shir-hashirim':       'Hooglied',
  // Latter Prophets
  yeshayahu:             'Jesaja',
  yirmeyahu:             'Jeremia',
  ekah:                  'Klaagliederen',
  yehezqel:              'Ezechiël',
  daniyel:               'Daniël',
  hoshea:                'Hosea',
  yoel:                  'Joël',
  amos:                  'Amos',
  obadyah:               'Obadja',
  yunah:                 'Jona',
  mikah:                 'Micha',
  nachum:                'Nahum',
  chabaquq:              'Habakuk',
  tsephanyah:            'Zefanja',
  chaggai:               'Haggaï',
  zekaryah:              'Zacharia',
  malaki:                'Maleachi',
  // Renewed Covenant
  mattithyahu:           'Mattheüs',
  marqos:                'Markus',
  luqas:                 'Lukas',
  yahuchanan:            'Johannes',
  acts:                  'Handelingen',
  romans:                'Romeinen',
  'corinthians-aleph':   '1 Korintiërs',
  'corinthians-beth':    '2 Korintiërs',
  galatians:             'Galaten',
  ephesians:             'Efeziërs',
  philippians:           'Filippenzen',
  colossians:            'Kolossenzen',
  'thessalonians-aleph': '1 Thessalonicenzen',
  'thessalonians-beth':  '2 Thessalonicenzen',
  'timothy-aleph':       '1 Timotheüs',
  'timothy-beth':        '2 Timotheüs',
  titus:                 'Titus',
  philemon:              'Filemon',
  hebrews:               'Hebreeën',
  james:                 'Jakobus',
  'kepha-aleph':         '1 Petrus',
  'kepha-beth':          '2 Petrus',
  'yahuchanan-aleph':    '1 Johannes',
  'yahuchanan-beth':     '2 Johannes',
  'yahuchanan-gimel':    '3 Johannes',
  yahudah:               'Judas',
  revelation:            'Openbaring',
  // Extra-canonical
  chanok:                '1 Ḥanok',
  jubilees:              'Jubileeën',
  jasher:                'Jasher',
  'baruk-aleph':         '1 Baruk',
  'baruk-beth':          '2 Baruk',
  '1-esdras':            '1 Esdras',
  '2-esdras':            '2 Esdras',
  tobit:                 'Tobit',
  judith:                'Judith',
  'maccabees-aleph':     '1 Makkabeeën',
  'maccabees-beth':      '2 Makkabeeën',
  'maccabees-gimel':     '3 Makkabeeën',
  'maccabees-dalet':     '4 Makkabeeën',
  wisdom:                'Wijsheid van Salomo',
  sirach:                'Sirach',
  'psalms-solomon':      'Psalmen van Salomo',
  'odes-solomon':        'Oden van Salomo',
}

export function getBookNameNl(slug: string, fallback: string): string {
  return BOOK_NAMES_NL[slug] ?? fallback
}
